# -*- encoding: utf-8 -*-
from alighi.models import Lando, LandoKategorio

landoj = [
 (u'Afganio', u'AF'),
 (u'Centr-Afrika Respubliko', u'CF'),
 (u'Alando', u'AX'),
 (u'Albanio', u'AL'),
 (u'Germanio', u'DE'),
 (u'Alĝerio', u'DZ'),
 (u'Usona Samoo', u'AS'),
 (u'Andoro', u'AD'),
 (u'Angvilo', u'AI'),
 (u'Angolo', u'AO'),
 (u'Antarktio', u'AQ'),
 (u'Unuiĝintaj Arabaj Emirlandoj', u'AE'),
 (u'Antigvo-Barbudo', u'AG'),
 (u'Argentino', u'AR'),
 (u'Armenio', u'AM'),
 (u'Arubo', u'AW'),
 (u'Aŭstralio', u'AU'),
 (u'Aŭstrio', u'AT'),
 (u'Azerbajĝano', u'AZ'),
 (u'Bahamoj', u'BS'),
 (u'Bangladeŝo', u'BD'),
 (u'Barbado', u'BB'),
 (u'Barejno', u'BH'),
 (u'Belgio', u'BE'),
 (u'Belizo', u'BZ'),
 (u'Benino', u'BJ'),
 (u'Bermudo', u'BM'),
 (u'Belorusio', u'BY'),
 (u'Britaj Virgulininsuloj', u'VG'),
 (u'Usonaj Virgulininsuloj', u'VI'),
 (u'Ebura Bordo', u'CI'),
 (u'Bolivio', u'BO'),
 (u'Bosnio kaj Hercegovino', u'BA'),
 (u'Bocvano', u'BW'),
 (u'Buvetinsulo', u'BV'),
 (u'Brazilo', u'BR'),
 (u'Brunejo', u'BN'),
 (u'Bulgario', u'BG'),
 (u'Burkino', u'BF'),
 (u'Burundo', u'BI'),
 (u'Butano', u'BT'),
 (u'Kristnaskinsulo', u'CX'),
 (u'Kokosinsuloj', u'CC'),
 (u'Kukinsuloj', u'CK'),
 (u'Danio', u'DK'),
 (u'Ĝibutio', u'DJ'),
 (u'Dominiko', u'DM'),
 (u'Domingo', u'DO'),
 (u'Egiptio', u'EG'),
 (u'Orienta Timoro', u'TL'),
 (u'Ekvadoro', u'EC'),
 (u'Ekvatora Gvineo', u'GQ'),
 (u'Eritreo', u'ER'),
 (u'Britio', u'GB'),
 (u'Rumanio', u'RO'),
 (u'Rusio', u'RU'),
 (u'Slovakio', u'SK'),
 (u'Slovenio', u'SI'),
 (u'Hispanio', u'ES'),
 (u'Usono', u'US'),
 (u'Usonaj Malgrandaj Insuloj', u'UM'),
 (u'Estonio', u'EE'),
 (u'Etiopio', u'ET'),
 (u'Ferooj', u'FO'),
 (u'Fiĝioj', u'FJ'),
 (u'Filipinoj', u'PH'),
 (u'Finnlando', u'FI'),
 (u'Francio', u'FR'),
 (u'Franca Gviano', u'GF'),
 (u'Franca Polinezio', u'PF'),
 (u'Gabono', u'GA'),
 (u'Gambio', u'GM'),
 (u'Kartvelio', u'GE'),
 (u'Ganao', u'GH'),
 (u'Ĝibraltaro', u'GI'),
 (u'Gvineo', u'GN'),
 (u'Gvineo Bisaŭa', u'GW'),
 (u'Grenado', u'GD'),
 (u'Grekio', u'GR'),
 (u'Gronlando', u'GL'),
 (u'Gvadelupo', u'GP'),
 (u'Gvamo', u'GU'),
 (u'Gvatemalo', u'GT'),
 (u'Gvernsejo', u'GG'),
 (u'Gujano', u'GY'),
 (u'Haitio', u'HT'),
 (u'Insulo Herdo kaj insuloj Makdonaldaj', u'HM'),
 (u'Sudafriko', u'ZA'),
 (u'Sud-Georgio kaj Sud-Sandviĉinsuloj', u'GS'),
 (u'Sud-Koreio', u'KR'),
 (u'Francaj Sudaj Teritorioj', u'TF'),
 (u'Nederlando', u'NL'),
 (u'Nederlandaj Antiloj', u'AN'),
 (u'Honduro', u'HN'),
 (u'Honkongo', u'HK'),
 (u'Hungario', u'HU'),
 (u'Barato', u'IN'),
 (u'Indonezio', u'ID'),
 (u'Nord-Koreio', u'KP'),
 (u'Nord-Marianoj', u'MP'),
 (u'Irako', u'IQ'),
 (u'Irano', u'IR'),
 (u'Irlando', u'IE'),
 (u'Islando', u'IS'),
 (u'Israelo', u'IL'),
 (u'Italio', u'IT'),
 (u'Jamajko', u'JM'),
 (u'Japanio', u'JP'),
 (u'Ĵersejo', u'JE'),
 (u'Jordanio', u'JO'),
 (u'Kabo-Verdo', u'CV'),
 (u'Kajmaninsuloj', u'KY'),
 (u'Nov-Kaledonio', u'NC'),
 (u'Kameruno', u'CM'),
 (u'Kanado', u'CA'),
 (u'Kamboĝo', u'KH'),
 (u'Kazaĥio', u'KZ'),
 (u'Kenjo', u'KE'),
 (u'Kirgizio', u'KG'),
 (u'Kiribato', u'KI'),
 (u'Kolombio', u'CO'),
 (u'Komoroj', u'KM'),
 (u'Respubliko Kongo', u'CG'),
 (u'Demokratia Respubliko Kongo', u'CD'),
 (u'Kostariko', u'CR'),
 (u'Kroatio', u'HR'),
 (u'Kubo', u'CU'),
 (u'Kuvajto', u'KW'),
 (u'Laoso', u'LA'),
 (u'Lesoto', u'LS'),
 (u'Latvio', u'LV'),
 (u'Libano', u'LB'),
 (u'Liberio', u'LR'),
 (u'Libio', u'LY'),
 (u'Liĥtenŝtejno', u'LI'),
 (u'Litovio', u'LT'),
 (u'Luksemburgo', u'LU'),
 (u'Madagaskaro', u'MG'),
 (u'Makao', u'MO'),
 (u'Makedonio', u'MK'),
 (u'Malajzio', u'MY'),
 (u'Malavio', u'MW'),
 (u'Insuloj Falklandoj', u'FK'),
 (u'Maldivoj', u'MV'),
 (u'Malio', u'ML'),
 (u'Malto', u'MT'),
 (u'Mankso', u'IM'),
 (u'Maroko', u'MA'),
 (u'Marŝala Insularo', u'MH'),
 (u'Martiniko', u'MQ'),
 (u'Maŭritanio', u'MR'),
 (u'Maŭricio', u'MU'),
 (u'Majoto', u'YT'),
 (u'Okcidenta Saharo', u'EH'),
 (u'Meksiko', u'MX'),
 (u'Federacio de Mikronezio', u'FM'),
 (u'Moldavio', u'MD'),
 (u'Monako', u'MC'),
 (u'Mongolio', u'MN'),
 (u'Montenegro', u'ME'),
 (u'Moncerato', u'MS'),
 (u'Mozambiko', u'MZ'),
 (u'Birmo', u'MM'),
 (u'Namibio', u'NA'),
 (u'Nauro', u'NR'),
 (u'Nepalo', u'NP'),
 (u'Niĝero', u'NE'),
 (u'Niĝerio', u'NG'),
 (u'Nikaragvo', u'NI'),
 (u'Niuo', u'NU'),
 (u'Norfolkinsulo', u'NF'),
 (u'Norvegio', u'NO'),
 (u'Omano', u'OM'),
 (u'Brita Hindoceana Teritorio', u'IO'),
 (u'Pakistano', u'PK'),
 (u'Palaŭo', u'PW'),
 (u'Palestino', u'PS'),
 (u'Panamo', u'PA'),
 (u'Papuo-Nov-Gvineo', u'PG'),
 (u'Paragvajo', u'PY'),
 (u'Peruo', u'PE'),
 (u'Pitkarna Insularo', u'PN'),
 (u'Pollando', u'PL'),
 (u'Portugalio', u'PT'),
 (u'Porto-Riko', u'PR'),
 (u'Kataro', u'QA'),
 (u'Reunio', u'RE'),
 (u'Ruando', u'RW'),
 (u'Sankta-Piero kaj Mikelono', u'PM'),
 (u'Salvadoro', u'SV'),
 (u'Salomonoj', u'SB'),
 (u'Samoo', u'WS'),
 (u'Sankta Vincento kaj la Grenadinoj', u'VC'),
 (u'Sankta-Kito kaj Neviso', u'KN'),
 (u'San-Marino', u'SM'),
 (u'Sao-Tomeo kaj Principeo', u'ST'),
 (u'Sankta Heleno', u'SH'),
 (u'Sankta Lucio', u'LC'),
 (u'Sauda Arabio', u'SA'),
 (u'Senegalo', u'SN'),
 (u'Serbio', u'RS'),
 (u'Sejŝeloj', u'SC'),
 (u'Siera-Leono', u'SL'),
 (u'Singapuro', u'SG'),
 (u'Sirio', u'SY'),
 (u'Somalio', u'SO'),
 (u'Sri-Lanko', u'LK'),
 (u'Svazilando', u'SZ'),
 (u'Sudano', u'SD'),
 (u'Svedio', u'SE'),
 (u'Svislando', u'CH'),
 (u'Surinamo', u'SR'),
 (u'Tajlando', u'TH'),
 (u'Tajvano', u'TW'),
 (u'Taĝikio', u'TJ'),
 (u'Tanzanio', u'TZ'),
 (u'Togo', u'TG'),
 (u'Tokelao', u'TK'),
 (u'Tongo', u'TO'),
 (u'Trinidado kaj Tobago', u'TT'),
 (u'Tunizio', u'TN'),
 (u'Turkio', u'TR'),
 (u'Turkoj kaj Kajkoj', u'TC'),
 (u'Turkmenio', u'TM'),
 (u'Tuvalo', u'TV'),
 (u'Ĉado', u'TD'),
 (u'Ĉeĥio', u'CZ'),
 (u'Ĉilio', u'CL'),
 (u'Ĉinio', u'CN'),
 (u'Ugando', u'UG'),
 (u'Ukrainio', u'UA'),
 (u'Urugvajo', u'UY'),
 (u'Uzbekio', u'UZ'),
 (u'Vanuatuo', u'VU'),
 (u'Vatikanurbo', u'VA'),
 (u'Belgio', u'BE'),
 (u'Belizo', u'BZ'),
 (u'Venezuelo', u'VE'),
 (u'Vjetnamio', u'VN'),
 (u'Valiso kaj Futuno', u'WF'),
 (u'Jemeno', u'YE'),
 (u'Zambio', u'ZM'),
 (u'Nov-Zelando', u'NZ'),
 (u'Zimbabvo', u'ZW'),
 (u'Kipro', u'CY'),
 (u'Svalbardo kaj Jan-Majen-insulo', u'SJ')
]

def enigu_landojn():
    kat = LandoKategorio.objects.all()[0]
    for (nomo, kodo) in landoj:
        lando = Lando(nomo=nomo, kodo=kodo, kategorio=kat)
        lando.save()